name: CI_python_project 
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  build_job:
    name: build_python_project
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout 2. Install Python 3. Install PyBuilder 4. Run Build
        uses: pybuilder/build@master
        with: 
          pyb-command: pyb package
        
