#Name für den Workflow
name: CI_python_project

on:
#Workflow wird für neue Daten, welche ins Repository hochgeladen werden automatisch ausgeführt
  push:
    branches:
    #Hauptbranch
    - main
    #auch manuelle Ausführung des Workflows möglich
  workflow_dispatch:
jobs:
#wie heisst der Job?
  build_job:
    name: build_python_project
    #auf welcher Betriebssystemversion läuft dieser Workflow?
    runs-on: ubuntu-latest
    #welche einzelnen Schritte sollen ausgeführt werden?
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
      - id: step2
        run: python -m virtualenv venv
      - id: step3
        run: cd Scripts
      - id: step4
        run: activate.bat
      - id: step5
        run: python -m pip install pybuilder
      - id: step6
        run: pyb package
        
